function C_s = coriolis_num(q1,q2,q1dot,q2dot,m1,m2,l1,lc1,lc2,I1,I2)
%CORIOLIS_NUM
%    C_s = CORIOLIS_NUM(Q1,Q2,Q1DOT,Q2DOT,M1,M2,L1,LC1,LC2,I1,I2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    10-Oct-2026 14:58:35

t2 = sin(q2);
C_s = reshape([-l1.*lc2.*m2.*q2dot.*t2,l1.*lc2.*m2.*q1dot.*t2,-l1.*lc2.*m2.*t2.*(q1dot+q2dot),0.0],[2,2]);
end
