function g_s = gravity_num(q1,q2,m1,m2,l1,lc1,lc2,g_acc)
%GRAVITY_NUM
%    G_S = GRAVITY_NUM(Q1,Q2,M1,M2,L1,LC1,LC2,G_ACC)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    10-Oct-2026 14:58:35

t2 = cos(q1);
t3 = q1+q2;
t4 = cos(t3);
g_s = [g_acc.*m2.*(l1.*t2+lc2.*t4)+g_acc.*lc1.*m1.*t2;g_acc.*lc2.*m2.*t4];
end
